x1 = int (input('Введите значение х1 = '))
y1 = int (input('Введите значение y1 = '))
x2 = int (input('Введите значение х2 = '))
y2 = int (input('Введите значение y2 = '))
print(float(((abs(abs(x1)-abs(x2)))**2 + (abs(abs(y1) - abs(y2)))**2))**0.5)